//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRenting_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Licenses
    {
        public int ID_MANY { get; set; }
        public int ID_Client { get; set; }
        public int ID_License { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Driver_License Driver_License { get; set; }
    }
}
