//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRenting_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int ID_Rent { get; set; }
        public int ID_Car { get; set; }
        public int ID_Client { get; set; }
        public System.DateTime PickUp_Date { get; set; }
        public int PickUp_Location_ID { get; set; }
        public System.DateTime DropDown_Date { get; set; }
        public int DropDown_Location_ID { get; set; }
        public int Total_Price { get; set; }
        public Nullable<int> ID_Credit_Card { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Client Client { get; set; }
        public virtual Credit_Card Credit_Card { get; set; }
    }
}
